services:
  web:
    build: .
    env_file:
      - prod.env
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn Billing.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
      "
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8001:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media:ro
      - ./staticfiles:/app/staticfiles:ro
    restart: unless-stopped